name: valentine_proposal
description: A basic pure-dart web app with ssr & automatic client hydration.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.9.3
  jaspr_router: ^0.3.0

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.0.4
  jaspr_builder: ^0.9.3
  jaspr_cli: ^0.9.3
  lints: ^2.1.0

jaspr:
  uses-ssr: true
  mode: client
  auto-hydrate: true
